# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - hosted-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Setup build for hosted-api
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          pwd
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd webapi 
          pip install -r requirements.txt
          pip install gunicorn
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4A88B60B0C9D4550900F45BA1DC19938 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E19EC918AF2D47158292ECC636808AA7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0109FBFAD2A14269A4FBEFDB4B982002 }}

      - name: 'Deploy to Azure Web App using gunicorn'
        id: deploy-to-webapp
        run:  |
          pwd
          source venv/bin/activate
          gunicorn -w 4 'api:app'
          